// https://eslint.org/docs/rules/#stylistic-issues
module.exports = {
  rules: {
    'array-bracket-newline': 0,
    'array-bracket-spacing': ['error', 'never'],
    'array-element-newline': 0,
    'block-spacing': ['error', 'never'],
    'brace-style': 'error',
    camelcase: 'error',
    'capitalized-comments': 'error',
    'comma-dangle': ['error', 'always'],
    'comma-spacing': ['error', {after: true, before: false}],
    'comma-style': ['error', 'first'],
    'computed-property-spacing': ['error', 'never'],
    'consistent-this': ['error', 'that'],
    'eol-last': 0,
    'func-call-spacing': ['error', 'never'],
    'func-name-matching': 'error',
    'func-names': ['error', 'always'],
    'func-style': 0,
    'function-paren-newline': 0,
    'id-blacklist': 0,
    'id-length': 'error',
    'id-match': 0,
    'implicit-arrow-linebreak': 0,
    indent: ['error', 2],
    'jsx-quotes': ['error', 'prefer-single'],
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    'line-comment-position': ['error', {position: 'above'}],
    'linebreak-style': 'error',
    'lines-around-comment': 'error',
    'lines-between-class-members': 'error',
    'max-depth': 'error',
    'max-len': 'error',
    'max-lines': 0,
    'max-lines-per-function': 0,
    'max-nested-callbacks': 'error',
    'max-params': 0,
    'max-statements': 0,
    'max-statements-per-line': 0,
    'multiline-comment-style': 'error',
    'multiline-ternary': 0,
    'new-cap': 'error',
    'new-parens': 'error',
    'newline-per-chained-call': 'error',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-continue': 'error',
    'no-inline-comments': 'error',
    'no-lonely-if': 'error',
    'no-mixed-operators': 'error',
    // 'no-mixed-spaces-and-tabs': 'error',
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': 'error',
    'no-negated-condition': 'error',
    'no-nested-ternary': 'error',
    'no-new-object': 'error',
    'no-plusplus': 'error',
    'no-restricted-syntax': 0,
    'no-tabs': 'error',
    'no-ternary': 0,
    'no-trailing-spaces': 'error',
    'no-underscore-dangle': 'error',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'nonblock-statement-body-position': 'error',
    'object-curly-newline': 0,
    'object-curly-spacing': 'error',
    'object-property-newline': 0,
    'one-var': 0,
    'one-var-declaration-per-line': 'error',
    'operator-assignment': 'error',
    'operator-linebreak': ['error', 'after'],
    'padded-blocks': ['error', 'never'],
    'padding-line-between-statements': 0,
    'prefer-object-spread': 'error',
    'quote-props': 0,
    quotes: ['error', 'single'],
    'require-jsdoc': 0,
    semi: 'error',
    'semi-spacing': 'error',
    'semi-style': 'error',
    'sort-keys': 'error',
    'sort-vars': 0,
    'space-before-blocks': 0,
    'space-before-function-paren': 0,
    'space-in-parens': 0,
    'space-infix-ops': 0,
    'space-unary-ops': 0,
    'spaced-comment': 0,
    'switch-colon-spacing': 0,
    'template-tag-spacing': 0,
    'unicode-bom': 0,
    'wrap-regex': 'error',
  },
};
