module.exports = {
  plugins: ['import'],
  rules: {
    'import/default': 'error',
    'import/dynamic-import-chunkname': 0,
    'import/export': 'error',
    'import/exports-last': 0,
    'import/first': 'error',
    'import/group-exports': 0,
    'import/max-dependencies': 'error',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/newline-after-import': 'error',
    'import/no-absolute-path': 'error',
    'import/no-amd': 'error',
    'import/no-anonymous-default-export': 'error',
    'import/no-commonjs': 'error',
    'import/no-cycle': 'error',
    'import/no-default-export': 0,
    'import/no-deprecated': 0,
    'import/no-duplicates': 'error',
    'import/no-dynamic-require': 'error',
    'import/no-extraneous-dependencies': 'error',
    'import/no-internal-modules': [
      'error',
      {
        allow: ['styled-icons/*'],
      },
    ],
    'import/no-mutable-exports': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-named-as-default': 0,
    'import/no-named-default': 'error',
    'import/no-namespace': 0,
    'import/no-nodejs-modules': 'error',
    'import/no-relative-parent-imports': 'error',
    'import/no-restricted-paths': 'error',
    'import/no-self-import': 'error',
    'import/no-unassigned-import': [
      'error',
      {
        allow: ['jest-styled-components'],
      },
    ],
    'import/no-unresolved': 0,
    'import/no-useless-path-segments': 'error',
    'import/no-webpack-loader-syntax': 'error',
    'import/order': 'error',
    'import/prefer-default-export': 0,
    'import/unambiguous': 'error',
  },
};
